<?php

use CodeIgniter\Router\RouteCollection;

/** @var RouteCollection $routes */

/*
 * Bound (:num) to a realistic id width.
 *
 * The framework default is [0-9]+ -- unlimited digits -- so a 21-digit id
 * reached the controller, hit a plain (int) cast, and PHP 8.5 raised
 * "the float-string ... is not representable as an int". CodeIgniter
 * promotes that warning to an ErrorException, which nothing catches, so
 * the request died as HTTP 500 and appended a ~1KB CRITICAL stack trace to
 * the log every time. Seven endpoints were reproducibly 500-able this way
 * by any logged-in user simply editing the URL.
 *
 * Ten digits covers the full range of an INT UNSIGNED primary key
 * (4294967295); the largest id in this database is four digits. So no
 * reachable URL stops matching -- an over-long id now simply fails to
 * route and gets the normal 404 instead of a server error.
 *
 * Must stay above the route definitions: placeholders are substituted as
 * each route is declared, so this has no effect on routes defined earlier.
 */
$routes->addPlaceholder('num', '[0-9]{1,10}');

$routes->get('/', 'Auth::login');

// Authentication Routes
$routes->get('auth/login', 'Auth::login');
$routes->post('auth/processLogin', 'Auth::processLogin');
$routes->get('auth/logout', 'Auth::logout');
$routes->get('auth/forgotPassword', 'Auth::forgotPassword');
$routes->post('auth/processForgotPassword', 'Auth::processForgotPassword');
$routes->get('auth/resetPassword/(:segment)', 'Auth::resetPassword/$1');
$routes->post('auth/processResetPassword', 'Auth::processResetPassword');

// Protected Application Routes
$routes->group('', ['filter' => 'authFilter'], function ($routes) {
    $routes->get('dashboard', 'Dashboard::index');

    // Changing your own password. Deliberately inside authFilter and outside
    // any accessFilter group: every signed-in account owns its own password,
    // whatever pages it has been granted. It carries no page_key for the same
    // reason -- an admin must not be able to revoke it.
    $routes->post('auth/changePassword', 'Auth::changePassword');

    // Centralized Select2 API Endpoints.
    //
    // These were the only data-returning routes in the app (besides
    // dashboard) with no second-stage authorization filter, so the Access
    // Rights system had no effect on them: any logged-in account could
    // enumerate the entire 469-row university master directory regardless of
    // which pages it had been granted.
    //
    // They cannot take a single page_key, because one endpoint feeds pickers
    // on several pages. accessFilter now accepts a comma-separated list where
    // ANY match grants access, so the rule becomes "you may read this
    // dropdown if you can reach at least one page that uses it" -- which is
    // exactly the set of users who legitimately need it, and no one else.
    $apiPages = 'accessFilter:students_new,universities,confirmations,regularization,reminders_university,reminders_student';

    $routes->group('', ['filter' => $apiPages], static function ($routes) {
        $routes->get('api/colleges', 'Api::colleges');
        $routes->get('api/states', 'Api::states');
        $routes->get('api/streams', 'Api::streams');
        $routes->get('api/academic-years', 'Api::academicYears');
    });
    
    // Student Form & Verification -- and the dispatch PDF it produces
    // (confirmed via grep: pdf/dispatch/(:segment) is only ever generated by
    // Students::storeBatch() and only ever opened from this page's own JS,
    // so it belongs to this page's access right, not Confirmations').
    $routes->group('', ['filter' => 'accessFilter:students_new'], function ($routes) {
        $routes->get('students/new', 'Students::newForm');
        $routes->get('students/generateCaseNo', 'Students::generateCaseNo');
        $routes->get('students/getCollegeInfo/(:num)', 'Students::getCollegeInfo/$1');
        $routes->post('students/storeBatch', 'Students::storeBatch');

        // Excel import. Inside this same accessFilter:students_new group on
        // purpose rather than under a seventh page_key: import writes exactly
        // what students/new writes, into the same table, producing the same
        // dispatch letter. A separate key would let an administrator grant
        // bulk-write without single-write, a distinction with no operational
        // meaning.
        $routes->get('students/import', 'Students::importForm');
        $routes->get('students/import/template', 'Students::importTemplate');
        $routes->post('students/import/preview', 'Students::importPreview');
        $routes->post('students/import/commit', 'Students::importCommit');
        $routes->get('pdf/dispatch/(:segment)', 'PdfController::dispatchLetter/$1');
        $routes->get('pdf/dispatchAccounts/(:segment)', 'PdfController::dispatchAccountsLetter/$1');
        $routes->get('students/history', 'Students::history');
        $routes->get('students/history/export', 'Students::historyExport');
        $routes->get('students/batch/(:segment)', 'Students::batchDetail/$1');
        $routes->get('students/getJson/(:num)', 'Students::getJson/$1');
        $routes->post('students/update/(:num)', 'Students::update/$1');
        $routes->post('students/delete/(:num)', 'Students::delete/$1');
    });

    // Universities Directory
    $routes->group('', ['filter' => 'accessFilter:universities'], function ($routes) {
        $routes->get('universities', 'Universities::index');
        $routes->get('universities/export', 'Universities::export');
        $routes->post('universities/store', 'Universities::store');
        $routes->get('universities/getJson/(:num)', 'Universities::getJson/$1');
        $routes->post('universities/update/(:num)', 'Universities::update/$1');
        // Deactivate/reactivate only, no delete: student_details keeps a copied
        // name/address rather than a foreign key to this table, so a deleted
        // university's name would vanish from every historical record.
        $routes->post('universities/toggleActive/(:num)', 'Universities::toggleActive/$1');
    });

    // Confirmations
    $routes->group('', ['filter' => 'accessFilter:confirmations'], function ($routes) {
        $routes->get('confirmations', 'Confirmations::index');
        $routes->get('confirmations/export', 'Confirmations::export');
        $routes->post('confirmations/store', 'Confirmations::store');
        $routes->get('confirmations/history', 'Confirmations::history');
        $routes->get('confirmations/history/export', 'Confirmations::historyExport');
        $routes->get('confirmations/batch/(:num)', 'Confirmations::batchDetail/$1');
        $routes->get('confirmations/eligibilityPdf/(:num)', 'Confirmations::eligibilityPdf/$1');
        $routes->post('confirmations/delete/(:num)', 'Confirmations::delete/$1');
    });

    // Regularization
    $routes->group('', ['filter' => 'accessFilter:regularization'], function ($routes) {
        $routes->get('regularization', 'Regularization::index');
        $routes->post('regularization/generateLetter', 'Regularization::generateLetter');
        $routes->get('regularization/history', 'Regularization::history');
        $routes->get('regularization/history/export', 'Regularization::historyExport');
        $routes->get('regularization/getJson/(:num)', 'Regularization::getJson/$1');
        $routes->post('regularization/update/(:num)', 'Regularization::update/$1');
        $routes->get('regularization/pdf/(:num)', 'Regularization::pdf/$1');
        $routes->post('regularization/delete/(:num)', 'Regularization::delete/$1');
    });

    // Reminders
    $routes->group('', ['filter' => 'accessFilter:reminders_university'], function ($routes) {
        $routes->get('reminders/university', 'Reminders::university');
        $routes->post('reminders/university', 'Reminders::university');
        $routes->get('reminders/university/export', 'Reminders::universityExport');
        $routes->post('reminders/generateUniversityReminder', 'Reminders::generateUniversityReminder');
        $routes->get('reminders/university/history', 'Reminders::universityHistory');
        $routes->get('reminders/university/history/export', 'Reminders::universityHistoryExport');
        $routes->get('reminders/university/batch/(:num)', 'Reminders::universityBatchDetail/$1');
        $routes->get('reminders/university/pdf/(:num)', 'Reminders::universityBatchPdf/$1');
    });
    $routes->group('', ['filter' => 'accessFilter:reminders_student'], function ($routes) {
        $routes->get('reminders/student', 'Reminders::student');
        $routes->post('reminders/generateStudentReminder', 'Reminders::generateStudentReminder');
        $routes->get('reminders/student/history', 'Reminders::studentHistory');
        $routes->get('reminders/student/history/export', 'Reminders::studentHistoryExport');
        $routes->get('reminders/student/pdf/(:num)', 'Reminders::studentPdf/$1');
        $routes->post('reminders/student/delete/(:num)', 'Reminders::studentDelete/$1');
    });

    // Settings (admin role only -- adminFilter stacks on top of authFilter,
    // since this group nests inside one already filtered by it).
    $routes->group('settings', ['filter' => 'adminFilter'], function ($routes) {
        $routes->get('/', 'Settings::index');
        $routes->get('activity-log', 'Settings::activityLog');

        $routes->get('institute', 'SettingsInstitute::index');
        $routes->post('institute/store', 'SettingsInstitute::store');

        $routes->get('academic-years', 'SettingsAcademicYears::index');
        $routes->post('academic-years/store', 'SettingsAcademicYears::store');
        $routes->get('academic-years/getJson/(:num)', 'SettingsAcademicYears::getJson/$1');
        $routes->post('academic-years/update/(:num)', 'SettingsAcademicYears::update/$1');
        $routes->post('academic-years/setCurrent/(:num)', 'SettingsAcademicYears::setCurrent/$1');
        $routes->post('academic-years/delete/(:num)', 'SettingsAcademicYears::delete/$1');

        $routes->get('courses', 'SettingsCourses::index');
        $routes->post('courses/store', 'SettingsCourses::store');
        $routes->get('courses/getJson/(:num)', 'SettingsCourses::getJson/$1');
        $routes->post('courses/update/(:num)', 'SettingsCourses::update/$1');
        // Deliberately no delete route: courses are deactivated, never
        // deleted, so historical student records keep their course name.
        $routes->post('courses/toggleActive/(:num)', 'SettingsCourses::toggleActive/$1');

        $routes->get('features', 'SettingsFeatures::index');
        $routes->post('features/store', 'SettingsFeatures::store');

        $routes->get('users', 'SettingsUsers::index');
        $routes->post('users/store', 'SettingsUsers::store');
        $routes->get('users/getJson/(:num)', 'SettingsUsers::getJson/$1');
        $routes->post('users/update/(:num)', 'SettingsUsers::update/$1');
        // Deliberately no delete route: legacy en_by-style columns reference
        // usernames by value, so users are deactivated, never deleted.
        $routes->post('users/toggleActive/(:num)', 'SettingsUsers::toggleActive/$1');

        $routes->get('numbering', 'SettingsNumbering::index');
        $routes->post('numbering/store', 'SettingsNumbering::store');

        $routes->get('letter-templates', 'SettingsLetterTemplates::index');
        $routes->post('letter-templates/footer/store', 'SettingsLetterTemplates::storeFooter');
        $routes->post('letter-templates/(:segment)/store', 'SettingsLetterTemplates::store/$1');
        $routes->post('letter-templates/(:segment)/preview', 'SettingsLetterTemplates::preview/$1');

        $routes->get('access-rights', 'SettingsAccessRights::index');
        $routes->post('access-rights/store', 'SettingsAccessRights::store');

        // Email (SMTP connection + wording). Sits with Settings, not with the
        // operational accessFilter:* pages -- SMTP credentials are as
        // sensitive as any other Settings value.
        $routes->get('mail', 'SettingsMail::index');
        $routes->post('mail/store', 'SettingsMail::store');
        $routes->post('mail/template/(:segment)/store', 'SettingsMail::storeTemplate/$1');
        $routes->post('mail/test', 'SettingsMail::sendTest');

        // Backup. Download takes (:num), never a filename, so the router
        // rejects a non-numeric segment before the controller runs -- the
        // first of several path-traversal gates (see
        // BackupService::resolveDownload()).
        $routes->get('backup', 'SettingsBackup::index');
        $routes->post('backup/sql', 'SettingsBackup::runSql');
        $routes->post('backup/excel', 'SettingsBackup::runExcel');
        $routes->post('backup/password/store', 'SettingsBackup::storePassword');
        $routes->post('backup/retention/store', 'SettingsBackup::storeRetention');
        $routes->get('backup/download/(:num)', 'SettingsBackup::download/$1');
        // POST, not GET: deleting a backup destroys a recovery point, so it
        // must not be reachable by a link, a prefetch or a crawler.
        $routes->post('backup/delete/(:num)', 'SettingsBackup::delete/$1');
    });

    // Bulk Email -- deliberately adminFilter, not one of the 6 operational
    // accessFilter:* pages. It is not in that page-key catalog, and unlike
    // those pages a mistake here contacts up to 500 external addresses in one
    // action, closer in risk to Settings than to day-to-day data entry.
    $routes->group('', ['filter' => 'adminFilter'], function ($routes) {
        $routes->get('bulk-email', 'BulkEmail::index');
        $routes->post('bulk-email/send', 'BulkEmail::send');
        $routes->get('bulk-email/log', 'BulkEmail::log');
        $routes->post('bulk-email/retry/(:num)', 'BulkEmail::retry/$1');
        $routes->post('bulk-email/retryAllFailed', 'BulkEmail::retryAllFailed');
    });
});
