<?php

use CodeIgniter\Router\RouteCollection;

/** @var RouteCollection $routes */

/*
 * Bound (:num) to a realistic id width.
 *
 * The framework default is [0-9]+ -- unlimited digits -- so a 21-digit id
 * reached the controller, hit a plain (int) cast, and PHP 8.5 raised
 * "the float-string ... is not representable as an int". CodeIgniter
 * promotes that warning to an ErrorException, which nothing catches, so
 * the request died as HTTP 500 and appended a ~1KB CRITICAL stack trace to
 * the log every time. Seven endpoints were reproducibly 500-able this way
 * by any logged-in user simply editing the URL.
 *
 * Ten digits covers the full range of an INT UNSIGNED primary key
 * (4294967295); the largest id in this database is four digits. So no
 * reachable URL stops matching -- an over-long id now simply fails to
 * route and gets the normal 404 instead of a server error.
 *
 * Must stay above the route definitions: placeholders are substituted as
 * each route is declared, so this has no effect on routes defined earlier.
 */
$routes->addPlaceholder('num', '[0-9]{1,10}');

$routes->get('/', 'Auth::login');

// Authentication Routes
$routes->get('auth/login', 'Auth::login');
$routes->post('auth/processLogin', 'Auth::processLogin');
$routes->get('auth/logout', 'Auth::logout');
$routes->get('auth/forgotPassword', 'Auth::forgotPassword');
$routes->post('auth/processForgotPassword', 'Auth::processForgotPassword');
$routes->get('auth/resetPassword/(:segment)', 'Auth::resetPassword/$1');
$routes->post('auth/processResetPassword', 'Auth::processResetPassword');

// Protected Application Routes
$routes->group('', ['filter' => 'authFilter'], function ($routes) {
    $routes->get('dashboard', 'Dashboard::index');

    // Changing your own password. Deliberately inside authFilter and outside
    // any accessFilter group: every signed-in account owns its own password,
    // whatever pages it has been granted. It carries no page_key for the same
    // reason -- an admin must not be able to revoke it.
    $routes->post('auth/changePassword', 'Auth::changePassword');

    // Centralized Select2 API Endpoints.
    //
    // These were the only data-returning routes in the app (besides
    // dashboard) with no second-stage authorization filter, so the Access
    // Rights system had no effect on them: any logged-in account could
    // enumerate the entire 469-row university master directory regardless of
    // which pages it had been granted.
    //
    // They cannot take a single page_key, because one endpoint feeds pickers
    // on several pages. accessFilter now accepts a comma-separated list where
    // ANY match grants access, so the rule becomes "you may read this
    // dropdown if you can reach at least one page that uses it" -- which is
    // exactly the set of users who legitimately need it, and no one else.
    // Each endpoint lists only the modules that ACTUALLY call it. The first
    // version used Permissions::viewKeys() -- all six modules -- for every
    // endpoint, which handed /api/colleges (and with it page-by-page access to
    // the whole 469-row university directory) to accounts granted nothing but
    // Candidate Reminders. That module's two screens contain no Select2 at all:
    // reminders/student.php is four free-text inputs, and only
    // reminders/university.php includes ajax_reminders_js.php. So the old rule
    // failed its own stated test of admitting "exactly the set of users who
    // legitimately need it, and no one else".
    //
    // The lists below are the result of grepping every view for each endpoint;
    // bulk-email also uses states/streams/academic-years but is admin-only, and
    // admin bypasses this filter by role.
    $apiFilter = static fn (string ...$modules): string => 'accessFilter:'
        . implode(',', array_map(static fn (string $m): string => $m . '.view', $modules));

    $routes->get('api/colleges', 'Api::colleges', ['filter' => $apiFilter(
        'students', 'universities', 'confirmations', 'regularization', 'reminders_university'
    )]);
    $routes->get('api/states', 'Api::states', ['filter' => $apiFilter('universities')]);
    $routes->get('api/streams', 'Api::streams', ['filter' => $apiFilter(
        'students', 'confirmations', 'regularization', 'reminders_university'
    )]);
    $routes->get('api/academic-years', 'Api::academicYears', ['filter' => $apiFilter(
        'students', 'confirmations', 'regularization', 'reminders_university'
    )]);
    
    // Student Form & Verification -- and the dispatch PDF it produces
    // (confirmed via grep: pdf/dispatch/(:segment) is only ever generated by
    // Students::storeBatch() and only ever opened from this page's own JS,
    // so it belongs to this page's access right, not Confirmations').
    $routes->group('', ['filter' => 'accessFilter:students.view'], function ($routes) {
        // students.create, not students.view. This route IS the data-entry
        // form -- there is nothing on it to read. Under students.view a
        // read-only clerk got a fully working multi-candidate form, keyed in a
        // whole batch, and only met the refusal at submit (storeBatch below
        // requires students.create), losing every field they had typed.
        $routes->get('students/new', 'Students::newForm', ['filter' => 'accessFilter:students.create']);
        $routes->get('students/generateCaseNo', 'Students::generateCaseNo');
        $routes->get('students/getCollegeInfo/(:num)', 'Students::getCollegeInfo/$1');
        $routes->post('students/storeBatch', 'Students::storeBatch', ['filter' => 'accessFilter:students.create']);

        // Excel import now has its own permission. Under the old page-level
        // scheme it deliberately shared students_new, because a separate KEY
        // would have granted bulk-write without single-write. That reasoning
        // does not survive per-action rights: students.create and
        // students.import are now independent, so the distinction is expressed
        // rather than avoided -- an office can let a clerk key candidates in
        // one at a time without handing them a 2,000-row upload.
        $routes->get('students/import', 'Students::importForm', ['filter' => 'accessFilter:students.import']);
        $routes->get('students/import/template', 'Students::importTemplate', ['filter' => 'accessFilter:students.import']);
        $routes->post('students/import/preview', 'Students::importPreview', ['filter' => 'accessFilter:students.import']);
        $routes->post('students/import/commit', 'Students::importCommit', ['filter' => 'accessFilter:students.import']);
        $routes->get('pdf/dispatch/(:segment)', 'PdfController::dispatchLetter/$1', ['filter' => 'accessFilter:students.print']);
        $routes->get('pdf/dispatchAccounts/(:segment)', 'PdfController::dispatchAccountsLetter/$1', ['filter' => 'accessFilter:students.print']);
        $routes->get('students/history', 'Students::history');
        $routes->get('students/history/export', 'Students::historyExport', ['filter' => 'accessFilter:students.export']);
        $routes->get('students/batch/(:segment)', 'Students::batchDetail/$1');
        $routes->get('students/getJson/(:num)', 'Students::getJson/$1');
        $routes->post('students/update/(:num)', 'Students::update/$1', ['filter' => 'accessFilter:students.edit']);
        $routes->post('students/delete/(:num)', 'Students::delete/$1', ['filter' => 'accessFilter:students.delete']);
    });

    // Universities Directory
    $routes->group('', ['filter' => 'accessFilter:universities.view'], function ($routes) {
        $routes->get('universities', 'Universities::index');
        $routes->get('universities/export', 'Universities::export', ['filter' => 'accessFilter:universities.export']);
        $routes->post('universities/store', 'Universities::store', ['filter' => 'accessFilter:universities.create']);
        $routes->get('universities/getJson/(:num)', 'Universities::getJson/$1');
        $routes->post('universities/update/(:num)', 'Universities::update/$1', ['filter' => 'accessFilter:universities.edit']);
        // Deactivate/reactivate only, no delete: student_details keeps a copied
        // name/address rather than a foreign key to this table, so a deleted
        // university's name would vanish from every historical record.
        $routes->post('universities/toggleActive/(:num)', 'Universities::toggleActive/$1', ['filter' => 'accessFilter:universities.toggle']);
    });

    // Confirmations
    $routes->group('', ['filter' => 'accessFilter:confirmations.view'], function ($routes) {
        $routes->get('confirmations', 'Confirmations::index');
        $routes->get('confirmations/export', 'Confirmations::export', ['filter' => 'accessFilter:confirmations.export']);
        $routes->post('confirmations/store', 'Confirmations::store', ['filter' => 'accessFilter:confirmations.create']);
        $routes->get('confirmations/history', 'Confirmations::history');
        $routes->get('confirmations/history/export', 'Confirmations::historyExport', ['filter' => 'accessFilter:confirmations.export']);
        $routes->get('confirmations/batch/(:num)', 'Confirmations::batchDetail/$1');
        $routes->get('confirmations/eligibilityPdf/(:num)', 'Confirmations::eligibilityPdf/$1', ['filter' => 'accessFilter:confirmations.print']);
        $routes->post('confirmations/delete/(:num)', 'Confirmations::delete/$1', ['filter' => 'accessFilter:confirmations.delete']);
    });

    // Regularization
    $routes->group('', ['filter' => 'accessFilter:regularization.view'], function ($routes) {
        // Same reasoning as students/new: this page is nothing but the letter
        // form, so regularization.view would hand a read-only user ten fields
        // and a Generate button that always 403s. History (below) stays on
        // .view -- that is the part there is something to read on.
        $routes->get('regularization', 'Regularization::index', ['filter' => 'accessFilter:regularization.create']);
        $routes->post('regularization/generateLetter', 'Regularization::generateLetter', ['filter' => 'accessFilter:regularization.create']);
        $routes->get('regularization/history', 'Regularization::history');
        $routes->get('regularization/history/export', 'Regularization::historyExport', ['filter' => 'accessFilter:regularization.export']);
        $routes->get('regularization/getJson/(:num)', 'Regularization::getJson/$1');
        $routes->post('regularization/update/(:num)', 'Regularization::update/$1', ['filter' => 'accessFilter:regularization.edit']);
        $routes->get('regularization/pdf/(:num)', 'Regularization::pdf/$1', ['filter' => 'accessFilter:regularization.print']);
        $routes->post('regularization/delete/(:num)', 'Regularization::delete/$1', ['filter' => 'accessFilter:regularization.delete']);
    });

    // Reminders
    $routes->group('', ['filter' => 'accessFilter:reminders_university.view'], function ($routes) {
        $routes->get('reminders/university', 'Reminders::university');
        $routes->post('reminders/university', 'Reminders::university');
        $routes->get('reminders/university/export', 'Reminders::universityExport', ['filter' => 'accessFilter:reminders_university.export']);
        $routes->post('reminders/generateUniversityReminder', 'Reminders::generateUniversityReminder', ['filter' => 'accessFilter:reminders_university.create']);
        $routes->get('reminders/university/history', 'Reminders::universityHistory');
        $routes->get('reminders/university/history/export', 'Reminders::universityHistoryExport', ['filter' => 'accessFilter:reminders_university.export']);
        $routes->get('reminders/university/batch/(:num)', 'Reminders::universityBatchDetail/$1');
        $routes->get('reminders/university/pdf/(:num)', 'Reminders::universityBatchPdf/$1', ['filter' => 'accessFilter:reminders_university.print']);
    });
    $routes->group('', ['filter' => 'accessFilter:reminders_student.view'], function ($routes) {
        $routes->get('reminders/student', 'Reminders::student');
        $routes->post('reminders/generateStudentReminder', 'Reminders::generateStudentReminder', ['filter' => 'accessFilter:reminders_student.create']);
        $routes->get('reminders/student/history', 'Reminders::studentHistory');
        $routes->get('reminders/student/history/export', 'Reminders::studentHistoryExport', ['filter' => 'accessFilter:reminders_student.export']);
        $routes->get('reminders/student/pdf/(:num)', 'Reminders::studentPdf/$1', ['filter' => 'accessFilter:reminders_student.print']);
        $routes->post('reminders/student/delete/(:num)', 'Reminders::studentDelete/$1', ['filter' => 'accessFilter:reminders_student.delete']);
    });

    // Settings (admin role only -- adminFilter stacks on top of authFilter,
    // since this group nests inside one already filtered by it).
    $routes->group('settings', ['filter' => 'adminFilter'], function ($routes) {
        $routes->get('/', 'Settings::index');
        $routes->get('activity-log', 'Settings::activityLog');

        $routes->get('institute', 'SettingsInstitute::index');
        $routes->post('institute/store', 'SettingsInstitute::store');

        $routes->get('academic-years', 'SettingsAcademicYears::index');
        $routes->post('academic-years/store', 'SettingsAcademicYears::store');
        $routes->get('academic-years/getJson/(:num)', 'SettingsAcademicYears::getJson/$1');
        $routes->post('academic-years/update/(:num)', 'SettingsAcademicYears::update/$1');
        $routes->post('academic-years/setCurrent/(:num)', 'SettingsAcademicYears::setCurrent/$1');
        $routes->post('academic-years/delete/(:num)', 'SettingsAcademicYears::delete/$1');

        $routes->get('courses', 'SettingsCourses::index');
        $routes->post('courses/store', 'SettingsCourses::store');
        $routes->get('courses/getJson/(:num)', 'SettingsCourses::getJson/$1');
        $routes->post('courses/update/(:num)', 'SettingsCourses::update/$1');
        // Deliberately no delete route: courses are deactivated, never
        // deleted, so historical student records keep their course name.
        $routes->post('courses/toggleActive/(:num)', 'SettingsCourses::toggleActive/$1');

        $routes->get('features', 'SettingsFeatures::index');
        $routes->post('features/store', 'SettingsFeatures::store');

        $routes->get('users', 'SettingsUsers::index');
        $routes->post('users/store', 'SettingsUsers::store');
        $routes->get('users/getJson/(:num)', 'SettingsUsers::getJson/$1');
        $routes->post('users/update/(:num)', 'SettingsUsers::update/$1');
        // Deliberately no delete route: legacy en_by-style columns reference
        // usernames by value, so users are deactivated, never deleted.
        $routes->post('users/toggleActive/(:num)', 'SettingsUsers::toggleActive/$1');

        $routes->get('numbering', 'SettingsNumbering::index');
        $routes->post('numbering/store', 'SettingsNumbering::store');

        $routes->get('letter-templates', 'SettingsLetterTemplates::index');
        $routes->post('letter-templates/footer/store', 'SettingsLetterTemplates::storeFooter');
        $routes->post('letter-templates/(:segment)/store', 'SettingsLetterTemplates::store/$1');
        $routes->post('letter-templates/(:segment)/preview', 'SettingsLetterTemplates::preview/$1');

        $routes->get('access-rights', 'SettingsAccessRights::index');
        // Permission cards for one staff account, swapped in when the admin
        // picks a different name. Inside the adminFilter group like the rest of
        // Settings, so it is not a way for staff to read the grant table.
        $routes->get('access-rights/user/(:num)', 'SettingsAccessRights::user/$1');
        $routes->post('access-rights/store', 'SettingsAccessRights::store');

        // Email (SMTP connection + wording). Sits with Settings, not with the
        // operational accessFilter:* pages -- SMTP credentials are as
        // sensitive as any other Settings value.
        $routes->get('mail', 'SettingsMail::index');
        $routes->post('mail/store', 'SettingsMail::store');
        $routes->post('mail/template/(:segment)/store', 'SettingsMail::storeTemplate/$1');
        $routes->post('mail/test', 'SettingsMail::sendTest');

        // Backup. Download takes (:num), never a filename, so the router
        // rejects a non-numeric segment before the controller runs -- the
        // first of several path-traversal gates (see
        // BackupService::resolveDownload()).
        $routes->get('backup', 'SettingsBackup::index');
        $routes->post('backup/sql', 'SettingsBackup::runSql');
        $routes->post('backup/excel', 'SettingsBackup::runExcel');
        $routes->post('backup/password/store', 'SettingsBackup::storePassword');
        $routes->post('backup/retention/store', 'SettingsBackup::storeRetention');
        $routes->get('backup/download/(:num)', 'SettingsBackup::download/$1');
        // POST, not GET: deleting a backup destroys a recovery point, so it
        // must not be reachable by a link, a prefetch or a crawler.
        $routes->post('backup/delete/(:num)', 'SettingsBackup::delete/$1');
    });

    // Bulk Email -- deliberately adminFilter, not one of the 6 operational
    // accessFilter:* pages. It is not in that page-key catalog, and unlike
    // those pages a mistake here contacts up to 500 external addresses in one
    // action, closer in risk to Settings than to day-to-day data entry.
    $routes->group('', ['filter' => 'adminFilter'], function ($routes) {
        $routes->get('bulk-email', 'BulkEmail::index');
        $routes->post('bulk-email/send', 'BulkEmail::send');
        $routes->get('bulk-email/log', 'BulkEmail::log');
        $routes->post('bulk-email/retry/(:num)', 'BulkEmail::retry/$1');
        $routes->post('bulk-email/retryAllFailed', 'BulkEmail::retryAllFailed');
    });
});
